spring:
  application:
    name: order-ms
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/database_spring?currentSchema=order
    username: postgres
    password: 12345678
    # JPA properties
    jpa:
      hibernate:
        ddl-auto: create-drop
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      open-in-view: false
      generate-ddl: true
  flyway:
    defaultSchema: order

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 5000
          multiplier: 1
          max-interval: 300000

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
  instance:
    instance-id: ${spring.application.name}:${random.int}
